#comment
#Github Actions

#имя экшона
name: My-Pipeline
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "Flask_deploy_ver_ ${{ github.sha }}" 
  
#на что будет реагировать и начинать работать
on: 
  push:
    branches:
    - main
#что будет делать: перечисление job'ов
jobs:
  test: 
    runs-on: ubuntu-latest
  
    steps:
      - name: Print Hello Message in test
        run: echo "Hello world from test-job"
        
      - name: Execute few commands
        run: |
          echo "hello message 1"
          echo "hello message 2"
          echo "App name: ${{ env.APPLICATION_NAME }}"
        
      - name: List current files
        run: ls -la
        
      - name: Git Clone my repo
        uses: actions/checkout@v1
          
      - name: List current files
        run: ls -la
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      VAR1 : "This is JOB level Var1"
      VAR2 : "This is JOB level Var2"
    
    steps:
      - name: Print Hello Message in deploy
        run: echo "Hello World from deploy-job"
      - name: Print env variables
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "LocallyVar = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is VAR in steps locally"
        
      - name: Printing deploymend packeg
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Lest test packages 1
        run: aws --version
      
      - name: Lest test packages 2
        run: zip --version
